= o-blog quick start

How to use https://github.com/renard/o-blog[o-blog].

http://renard.github.com/o-blog[Demo site].

== Quick start guide
First you need:

- http:www.gnu.org/s/emacs[emacs] (I assume you already have it)
- http://orgmode.org/[org-mode] (same as above)

If you don't have them, you should install them fist.

=== Setup

==== Using +el-get+

If you are using https://github.com/dimitri/el-get[el-get] it would be very
easy to install. All you need to do is to add +o-blog+ to +el-get-sources+
and type +M-x el-get-install o-blog+.

If you are using +el-get+ 4 or greater, you only need to type: +M-x
el-get-install o-blog+.

==== Manual setup
Start by cloning the +git+ repository from http:github.com[Github].

----
cd ~/.emacs.d
git clone https://github.com/renard/o-blog.git
----

And add following to your +~/.emacs.d/init.el+ file:

----
(add-to-list 'load-path "~/.emacs.d/o-blog")
(require 'o-blog)
----

=== Publish

Open the +~/.emacs.d/o-blog/example/sample.org+ file and type +M-x
org-publish-blog+. The result site would be published by default in
+~/.emacs.d/o-blog/out+.

See the +example/out/blog/index.html+ and +example/out/todo.html+' for more
details.


